# config.yaml

Question1:
 A1: 问题1
 B1: ___实例001：数字组合___
 C1: 题目 有四个数字：1、2、3、4，能组成多少个互不相同且无重复数字的三位数？各是多少？

Question2:
 A1: 问题2
 B1: ___实例002：“个税计算”___
 C1: 题目 企业发放的奖金根据利润提成。
    利润(I)低于或等于10万元时，奖金可提10%；
    利润高于10万元，低于20万元时，低于10万元的部分按10%提成，高于10万元的部分，可提成7.5%；
    20万到40万之间时，高于20万元的部分，可提成5%；
    40万到60万之间时高于40万元的部分，可提成3%；
    60万到100万之间时，高于60万元的部分，可提成1.5%，
    高于100万元时，超过100万元的部分按1%提成，
    从键盘输入当月利润I，求应发放奖金总数？

Question3:
 A1: 问题3
 B1: ____实例003：完全平方数____
 C1: 题目 一个整数，它加上100(A)后是一个完全平方数，再加上168(X)又是一个完全平方数，请问该数是多少？

Question4:
 A1: 问题4
 B1: ____实例004：当天是一年中的第几天 ____
 C1: 题目 输入某年某月某日，判断这一天是这一年的第几天？

Question5:
 A1: 问题5
 B1: ____ 实例005：三数排序 ____
 C1: 题目 输入三个整数x,y,z，请把这三个数由小到大输出。

Question6:
 A1: 问题6
 B1: ____ 实例006：斐波那契数列 ____
 C1: 题目 斐波那契数列是一位意大利的数学家，他闲着没事去研究兔子繁殖的过程，研究着就发现，
    可以写成这么一个序列：1，1，2，3，5，8，13，21… 
    也就是每个数等于它前两个数之和。那么给你第 n 个数，问F(n)是多少。

Question7:
 A1: 问题7
 B1: ____ 实例007：copy ____
 C1: 题目 将第一个列表的数据复制到第二个列表中。

Question8:
 A1: 问题8
 B1: ____ 实例008：九九乘法表 ____
 C1: 题目 输出 9(第一个数)*9(第二个数) 乘法口诀表

Question9:
 A1: 问题9
 B1: ____ 实例009：指定时间执行 ____
 C1: 题目 指定时间输出。

Question10:
 A1: 问题10
 B1: ____ 实例010：暂停x秒输出时间 ____
 C1: 题目 暂停一秒输出，并格式化当前时间。

Question11:
 A1: 问题11
 B1: ____ 实例011：养兔子 ____
 C1: 题目 有1(A)对兔子，从出生后第3(x)个月起每个月都生一对兔子，
    小兔子长到第三个月后每个月又生一对兔子，
    假如兔子都不死，问每个月的兔子总数为多少？

Question12:
 A1: 问题12
 B1: ____ 实例012： 100到200的素数 ____
 C1: 题目 判断101-200之间有多少个素数，并输出所有素数。

Question13:
 A1: 问题13
 B1: ____ 实例013：所有水仙花数 ____
 C1:     题目 打印出所有的"水仙花数"，
    所谓"水仙花数"是指一个三位数，
    其各位数字立方和等于该数本身。
    例如：153是一个"水仙花数"，
    因为153=1的三次方＋5的三次方＋3的三次方。

Question14:
 A1: 问题14
 B1: ____ 实例014：分解质因数 ____
 C1: 题目 将一个整数分解质因数。
    例如：输入90,打印出90=233*5。



Question15:
 A1: 问题15
 B1: ____ 实例015：分数归档 ____
 C1: 题目 利用条件运算符的嵌套来完成此题：
     学习成绩>=90分的同学用A表示，
     60-89分之间的用B表示，
     60分以下的用C表示。

Question16:
 A1: 问题16
 B1: ____ 实例016：输出日期  ____
 C1: 题目 输出指定格式的日期。

Question17:
 A1: 问题17
 B1: ____ 实例017：字符串构成  ____
 C1: 题目 输入一行字符，分别统计出其中英文字母、空格、数字和其它字符的个数。

Question18:
 A1: 问题18
 B1: ____ 实例018：复读机相加 ____
 C1: 题目 求s=a+aa+aaa+aaaa+aa…a的值，其中a是一个数字。
     例如2+22+222+2222+22222(此时共有5个数相加)，几个数相加由键盘控制。

Question19:
 A1: 问题19
 B1: ____ 实例019：完数 ____
 C1: 题目 一个数如果恰好等于它的因子之和，这个数就称为"完数"。
     例如6=1＋2＋3.编程找出1000以内的所有完数，(注意去重)。

Question20:
 A1: 问题20
 B1: ____ 实例020：高空抛物 ____
 C1:  题目 一球从100米高度自由落下，每次落地后反跳回原高度的一半；再落下，
      求它在第10次落地时，共经过多少米？第10次反弹多高？

Question21:
 A1: 问题21
 B1: ____ 实例021：猴子偷桃 ____
 C1: 题目 猴子吃桃问题：猴子第一天摘下若干个桃子，当即吃了一半，还不过瘾，又多吃了一个第二天早上又将剩下的桃子吃掉一半，又多吃了一个。
     以后每天早上都吃了前一天剩下的一半零一个。到第10天早上想再吃时，见只剩下一个桃子了。求第一天共摘了多少。

Question22:
 A1: 问题22
 B1: ____ 实例022：比赛对手 ____
 C1:  题目 两个乒乓球队进行比赛，各出三人。甲队为a,b,c三人，乙队为x,y,z三人。已抽签决定比赛名单。
      有人向队员打听比赛的名单。a说他不和x比，c说他不和x,z比，请编程序找出三队赛手的名单。

Question23:
 A1: 问题23
 B1: ____ 实例023：画菱形 ____
 C1: 题目 打印出如下图案（菱形）
        *
       ***
      *****
     *******
      *****
       ***
        *

Question24:
 A1: 问题24
 B1: ____ 实例024：斐波那契数列II ____
 C1: 题目 有一分数序列：2/1，3/2，5/3，8/5，13/8，21/13…求出这个数列的前20项之和。

Question25:
 A1: 问题25
 B1: ____ 实例025： 阶乘求和 ____
 C1: 题目 求1+2!+3!+…+20!的和。

Question26:
 A1: 问题26
 B1: ____ 实例026：递归求阶乘 ____
 C1: 题目 利用递归方法求5!。

Question27:
 A1: 问题27
 B1: ____ 例027：递归输出 ____
 C1: 题目 利用递归函数调用方式，将所输入的5个字符，以相反顺序打印出来。

Question28:
 A1: 问题28
 B1: ____ 实例028：递归求等差数列 ____
 C1: 题目 有5个人坐在一起，问第五个人多少岁？他说比第4个人大2岁。
     问第4个人岁数，他说比第3个人大2岁。问第三个人，又说比第2人大两岁。
     问第2个人，说比第一个人大两岁。最后问第一个人，他说是10岁。请问第五个人多大？

Question29:
 A1: 问题29
 B1: ____ 实例029：反向输出 ____
 C1: 题目 给一个不多于 n 位的正整数，
     要求：一、求它是几位数，二、逆序打印出各位数字

Question30:
 A1: 问题30
 B1: ____ 实例030：回文数 ____
 C1: 题目 一个5位数，判断它是不是回文数。
     即12321是回文数，个位与万位相同，十位与千位相同。

Question31:
 A1: 问题31
 B1: ____ 实例031：字母识词 ____
 C1: 题目 请输入星期几的第一个字母来判断一下是星期几，
     如果第一个字母一样，则继续判断第二个字母。

Question32:
 A1: 问题32
 B1: ____ 实例032：列表反向输出II ____
 C1: 题目 按相反的顺序输出列表的值。

Question33:
 A1: 问题33
 B1: ____实例033：列表转字符串____
 C1: 题目 按逗号分隔列表。

Question34:
 A1: 问题34
 B1: ____ 实例034：调用函数 ____
 C1: 题目 练习函数调用。

Question35:
 A1: 问题35
 B1: ____ 实例035：设置输出颜色 ____
 C1: 题目 文本颜色设置。

Question36:
 A1: 问题36
 B1: ____ 实例036：算素数 ____
 C1: 题目 求1-X之内的素数。

Question37:
 A1: 问题37
 B1: ____ 实例037：排序 ____
 C1: 题目 对10个数进行排序。

Question38:
 A1: 问题38
 B1: ____ 实例038：矩阵对角线之和 ____
 C1: 题目 求一个3*3矩阵主对角线元素之和。 

Question39:
 A1: 问题39
 B1: ____ 实例039：有序列表插入元素 ____
 C1: 题目 有一个已经排好序的数组。现输入一个数，要求按原来的规律将它插入数组中。

Question40:
 A1: 问题40
 B1: ____ 实例040：逆序列表 ____
 C1: 题目 将一个数组逆序输出。  

Question41:
 A1: 问题41
 B1: ____  ____
 C1: 

Question42:
 A1: 问题42
 B1: ____  ____
 C1: 

Question43:
 A1: 问题43
 B1: ____  ____
 C1: 

Question44:
 A1: 问题44
 B1: ____  ____
 C1: 

Question45:
 A1: 问题45
 B1: ____  ____
 C1: 

Question46:
 A1: 问题46
 B1: ____  ____
 C1: 

Question47:
 A1: 问题47
 B1: ____  ____
 C1: 

Question48:
 A1: 问题48
 B1: ____  ____
 C1: 

Question49:
 A1: 问题49
 B1: ____  ____
 C1: 

Question50:
 A1: 问题50
 B1: ____  ____
 C1: 

Question100:
 A1: 问题100
 B1: ____  ____
 C1: 